export const RUNTIME_REPOSITORY = Symbol("RUNTIME_REPOSITORY");
export const RUNTIME_ID_GENERATOR = Symbol("RUNTIME_ID_GENERATOR");
export const RUNTIME_VERSION_READER = Symbol("RUNTIME_VERSION_READER");
